// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuNc0VDdp8u4O4ajg0k1Ct9CUsejE2jI',
    appId: '1:781524162883:web:df76957347e90194a377f6',
    messagingSenderId: '781524162883',
    projectId: 'traxx-e1232',
    authDomain: 'traxx-e1232.firebaseapp.com',
    storageBucket: 'traxx-e1232.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62YBIJlL0uBk55nr1mXli7AC9zjTgwlY',
    appId: '1:781524162883:android:f723fa69ae867dffa377f6',
    messagingSenderId: '781524162883',
    projectId: 'traxx-e1232',
    storageBucket: 'traxx-e1232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADybJJn29gs65j451QvHNCTOm3l3d77yw',
    appId: '1:781524162883:ios:4894131d18b11b82a377f6',
    messagingSenderId: '781524162883',
    projectId: 'traxx-e1232',
    storageBucket: 'traxx-e1232.firebasestorage.app',
    iosClientId: '781524162883-5sv2kncfvmumu0se62cuhr5a7ts4bk9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.traxxWepapp',
  );

}